name: build_qlinklib

on:
  workflow_dispatch: 

jobs:
  job_windows_msvc:
    name: windows MSVC
    runs-on: windows-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: environment preparation
        run: mkdir .\build

      - name: project configuration in release
        working-directory: build
        run: >
          cmake ..
          -G "Visual Studio 17 2022" -A Win32
          -DCMAKE_EXE_LINKER_FLAGS="/NODEFAULTLIB:MSVCRT"
          -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"
          -DCMAKE_BUILD_TYPE=Release

      - name: project PACKAGE
        working-directory: build
        run: cmake --build . --config Release

      - name: List directory structure
        run: tree /F build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qlink
          path: |
            build\dll