name: 打包上传 stlink

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config:
          - name: stlink原版
            change: false
          - name: stlink修改版
            change: true
    steps:
      - name: 克隆项目 stlink
        run: git clone https://github.com/stlink-org/stlink.git

      - name: 修改 CMakeLists.txt
        if: matrix.config.change == true
        working-directory: stlink
        run: |
          # 替换 "CMAKE_CHIPS_DIR" > "./chips"
          (Get-Content CMakeLists.txt) -replace '-DSTLINK_CHIPS_DIR="\$\{CMAKE_CHIPS_DIR\}"', '-DSTLINK_CHIPS_DIR="./chips"' | Set-Content CMakeLists.txt
          type CMakeLists.txt

      - name: 代码注入 chipid.c
        if: matrix.config.change == true
        working-directory: stlink/src/stlink-lib
        run: |
          Add-Content chipid.c '`r`n#include"devicelist_func.c"`r`n#include"devicelist_const.c"'
          type chipid.c

      - name: 复制 devicelist 文件
        if: matrix.config.change == true
        working-directory: stlink
        run: |
          Copy-Item -Path "../devicelist_func.c"  -Destination "./src/stlink-lib/devicelist_func.c"  -Force
          Copy-Item -Path "../devicelist_const.c" -Destination "./src/stlink-lib/devicelist_const.c" -Force


      - name: 创建 build 目录
        working-directory: stlink
        run: mkdir ./build

      - name: 编译项目
        working-directory: stlink/build
        run: >
          cmake ..
          -G "Visual Studio 17 2022" -A Win32
          -DCMAKE_EXE_LINKER_FLAGS="/NODEFAULTLIB:MSVCRT"
          -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"

      - name: 打包项目
        working-directory: stlink/build
        run: |
          cmake --build . --config Release --target PACKAGE
          tree

      - name: 调整目录结构
        if: matrix.config.change == true
        working-directory: stlink/build/dist
        run: |
          $ZipFile = Get-ChildItem "stlink-*.zip" | Select-Object -First 1
          Expand-Archive -Path $ZipFile.Name -DestinationPath .
          if (Test-Path $ZipFile.BaseName) {
              Get-ChildItem -Path $ZipFile.BaseName | Move-Item -Destination . -Force
              Remove-Item $ZipFile.BaseName -Recurse -Force
          }
          Remove-Item $ZipFile.Name -Recurse -Force

      - name: 移动 chips 目录
        if: matrix.config.change == true
        working-directory: stlink/build/dist
        run: |
          Move-Item -Path "Program Files (x86)\stlink\config\chips" -Destination "bin\chips" -Force
          Remove-Item -Path "Program Files (x86)" -Recurse -Force

      - name: 上传 stlink
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.name }}
          path: stlink/build/dist
