name: 静态编译 stlink

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 克隆项目 stlink
        run: git clone https://github.com/stlink-org/stlink.git

      - name: 代码注入 chipid.c
        working-directory: stlink/src/stlink-lib
        run: |
          if (Test-Path chipid.c) {
              Add-Content chipid.c @"
              `r`n
              void set_devicelist(struct stlink_chipid_params *set) {
                  devicelist = set;
              }
              "@
              Write-Host "已成功注入代码到 chipid.c"
          } else {
              Write-Host "chipid.c不存在, 跳过代码注入"
          }

      - name: 创建 build 目录
        working-directory: stlink
        run: mkdir ./build

      - name: 编译项目
        working-directory: stlink/build
        run: >
          cmake ..
          -G "Visual Studio 17 2022" -A Win32
          -DCMAKE_EXE_LINKER_FLAGS="/NODEFAULTLIB:MSVCRT"
          -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"
          -DCMAKE_BUILD_TYPE=Release

      - name: 打包项目
        working-directory: stlink/build
        run: |
          cmake --build . --target PACKAGE
          tree

      - name: 上传 stlink
        uses: actions/upload-artifact@v4
        with:
          name: stlink
          path: |
            stlink/build/dist
            stlink/src/stlink-lib/chipid.c
            