name: build_stlink

on:
  push:
  workflow_dispatch: 

jobs:
  job_windows_msvc:
    name: windows MSVC
    runs-on: windows-latest
    steps:
      - name: 克隆项目 stlink
        run: git clone https://github.com/stlink-org/stlink.git

      - name: 修改 CMakeLists.txt
        working-directory: stlink
        shell: pwsh
        run: |
          (Get-Content CMakeLists.txt) -replace '-DSTLINK_CHIPS_DIR="\$\{CMAKE_CHIPS_DIR\}"', '-DSTLINK_CHIPS_DIR="./chips"' | Set-Content CMakeLists.txt
          type CMakeLists.txt

      - name: 编译项目
        working-directory: stlink
        run: >
          mkdir ./build
          cd build
          cmake ..
          -G "Visual Studio 17 2022" -A Win32
          -DCMAKE_EXE_LINKER_FLAGS="/NODEFAULTLIB:MSVCRT"
          -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"
          -DCMAKE_BUILD_TYPE=Release

      - name: 打包项目
        working-directory: stlink/build
        run: cmake --build . --config Release --target PACKAGE


      - name: 调整目录结构
        shell: pwsh
        working-directory: stlink/build/dist
        run: |
          tree
          Expand-Archive -Path "stlink-*.zip" -DestinationPath .
          Get-ChildItem -Directory "stlink-*" | Rename-Item -NewName "stlink-new" -Force
          cd stlink-new
          Move-Item -Path "Program Files (x86)\stlink\config\chips" -Destination "bin\chips" -Force
          Remove-Item -Path "Program Files (x86)" -Recurse -Force
          tree

      - name: 上传 stlink
        uses: actions/upload-artifact@v4
        with:
          name: stlink-package
          path: stlink/build/dist/stlink-new
