name: build_stlink

on:
  workflow_dispatch: # 手动触发工作流

jobs:
  job_windows_msvc:
    name: windows MSVC
    runs-on: windows-latest
    steps:
      - name: Clone stlink
        run: git clone https://github.com/stlink-org/stlink.git

      - name: environment preparation
        working-directory: stlink
        run: mkdir .\build\release

      - name: project configuration in release
        working-directory: stlink/build/release
        run: >
          cmake ../../ 
          -G "Visual Studio 17 2022" -A Win32
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_SHARED_LIBS=OFF
          -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"
          -DCMAKE_EXE_LINKER_FLAGS="/NODEFAULTLIB:MSVCRT"
          -DSTLINK_USE_SYSTEM_LIBUSB=FALSE

      - name: project build in release
        working-directory: stlink/build/release
        run: cmake --build . --config Release --target ALL_BUILD

      - name: Verify static linking
        working-directory: stlink/build/release/bin/Release
        run: |
          dumpbin /dependents st-flash.exe
          dumpbin /dependents st-info.exe

      - name: project installation
        working-directory: stlink/build/release
        run: cmake --build . --config Release --target INSTALL

      - name: List directory structure
        run: tree /F stlink\build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stlink-static
          path: |
            stlink\build\release\bin\Release\*.exe
            stlink\build\release\lib\Release\*.lib
            stlink\config\chips