name: Auto Commit Demo

on:
  workflow_dispatch:
  
jobs:
  auto-commit:
    runs-on: windows-latest

    permissions:
      contents: write  # 必须开启写权限

    steps:
    - name: Checkout 代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: 配置用户名邮箱
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"










    - name: Commit 修改
      id: commit
      run: |
        git add .
        $commitMessage = "auto-commit-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
        git commit -m "$commitMessage"
      continue-on-error: true

    - name: Push 修改
      if: steps.commit.outcome == 'success'
      run: |
        git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main