name: 运行 tcc

on:
  push:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆项目 stlink
        run: git clone https://github.com/stlink-org/stlink.git

      - name: 安装 tcc
        # sudo apt-get update -qq  # 静默更新源列表
        run: sudo apt-get install -y tcc libusb-1.0-0-dev

      - name: 创建头文件
        working-directory: stlink/inc
        run: |
          cat << EOF > version.h
          #ifndef VERSION_H
          #define VERSION_H
          #define STLINK_VERSION "xxxxxx"
          #define STLINK_VERSION_MAJOR 1
          #define STLINK_VERSION_MINOR 8
          #define STLINK_VERSION_PATCH 0
          int ugly_log(int level, const char *tag, const char *format, ...){return 0;}
          #endif // VERSION_H
          EOF

      - name: tcc
        working-directory: stlink
        run: tcc -Iinc -Isrc/stlink-lib -I/usr/include/libusb-1.0 -run ./src/stlink-lib/chipid.c





