name: 运行 tcc

on:
  push:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆项目 stlink
        run: git clone https://github.com/stlink-org/stlink.git

      - name: 安装 tcc libusb
        run: |
          sudo apt-get update -qq  # 静默更新源列表
          sudo apt-get install -y tcc libusb-1.0-0-dev

      - name: 创建头文件
        working-directory: stlink
        run: |

          cat << EOF >> inc/version.h
          #ifndef VERSION_H
          #define VERSION_H
          #define STLINK_VERSION "xxxxxx"
          #define STLINK_VERSION_MAJOR 1
          #define STLINK_VERSION_MINOR 8
          #define STLINK_VERSION_PATCH 0
          #endif // VERSION_H
          EOF

          cat << EOF > src/stlink-lib/main.c
          #define STLINK_HAVE_DIRENT_H
          #include "chipid.c"
          int32_t ugly_log(int32_t level, const char *tag, const char *format, ...){return 0;}
          void stlink_print_devicelist() {
            struct stlink_chipid_params *dev = NULL;
            printf("\n\nstruct stlink_chipid_params devicelist_const[] ={{\"unknow\"},");
            for (dev = devicelist; dev != NULL; dev = dev->next) {
              printf("\n{");
              printf("\"%s\",",dev->dev_type);
              printf("NULL,");
              printf("0x%x," , dev->chip_id);
              printf("%d,"   , dev->flash_type);
              printf("0x%x," , dev->flash_size_reg);
              printf("0x%x," , dev->flash_pagesize);
              printf("0x%x," , dev->sram_size);
              printf("0x%x," , dev->bootrom_base);
              printf("0x%x," , dev->bootrom_size);
              printf("0x%x," , dev->option_base);
              printf("0x%x," , dev->option_size);
              printf("%d,"   , dev->flags);
              printf("0x%x," , dev->otp_base);
              printf("0x%x"  , dev->otp_size);
              printf("},");
            }
            printf("{NULL}\n};");
          }
          int main() {
            init_chipids("config/chips");
            stlink_print_devicelist();
            return 0;
          }
          EOF

      - name: tcc
        working-directory: stlink
        run: tcc -Iinc -Isrc/stlink-lib -I/usr/include/libusb-1.0 -run ./src/stlink-lib/main.c >> a.txt


      - name: 上传 stlink
        uses: actions/upload-artifact@v4
        with:
          name: aaaa
          path: stlink/a.txt


