name: 运行 tcc

on:
  push:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆项目 stlink
        run: git clone https://github.com/stlink-org/stlink.git

      - name: 安装 tcc
        run: |
          # sudo apt-get update -qq  # 静默更新源列表
          sudo apt-get install tcc

      - name: tcc
        working-directory: stlink
        run: tcc -Iinc -run ./src/stlink-lib/chipid.c





