name: Compile Hello World

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:

  - name: Set up Visual Studio shell
    uses: egor-tensin/vs-shell@v2
    with:
      arch: x86

    - name: Compile Hello World
      run: |
        @"
        #include <stdio.h>
        int main() {
            printf("Hello, World!\n");
            return 0;
        }
        "@ | Add-Content hello.c
        cl.exe /nologo hello.c /Fe:hello.exe