name: 编译 QLink

on:
  workflow_dispatch: 

jobs:
  job_windows_msvc:
    name: 创建 QLink.dll
    runs-on: windows-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: environment preparation
        run: mkdir .\build

      - name: cmake configure
        working-directory: build
        run: >
          cmake ..
          -G "Visual Studio 17 2022" -A Win32
          -DCMAKE_EXE_LINKER_FLAGS="/NODEFAULTLIB:MSVCRT"
          -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"

      - name: Build Project
        working-directory: build
        run: cmake --build . --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QLink
          path: |
            build\dll